package com.campusbooking.web.model;

// This should be an enum, not a class.
public enum Status {
    PENDING_STAFF_APPROVAL,
    PENDING_STAFF_APPROVAL_REAPPLIED,
    PENDING_HOD_APPROVAL,
    PENDING_HOD_APPROVAL_REAPPLIED,
    PENDING_DEAN_APPROVAL,
    PENDING_DEAN_APPROVAL_REAPPLIED,
    PENDING_PRINCIPAL_APPROVAL,
    PENDING_PRINCIPAL_APPROVAL_REAPPLIED,
    APPROVED,
    REJECTED
}